query ListAllUsers @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users.") {
  users {
    id
  }
}

query GetUserById($id: UUID!) @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users.") {
  user(id: $id) {
    id
  }
}

mutation CreateUser($id: UUID!) @auth(level: USER) {
  user_insert(data: {
    id: $id,
    displayName: "User",
    email: "user@example.com",
    createdAt_expr: "request.time"
  })
}

mutation UpdateUser($id: UUID!) @auth(level: USER) {
  user_update(key: {
    id: $id
  }, data: {
    id: $id
  })
}